# Tabla de cadenas: (clave, es-PE, es-419 (None = igual), pt-BR, en)
STRINGS = [
    # Comunes
    ("app_name", "APhid", None, "APhid", "APhid"),
    ("pending_data", "dato pendiente", None, "dado pendente", "data pending"),
    ("cd_info", "Información", None, "Informação", "Information"),
    ("cd_warning", "Advertencia", None, "Aviso", "Warning"),
    ("cd_back", "Volver", None, "Voltar", "Back"),
    ("action_save", "Guardar", None, "Salvar", "Save"),
    ("action_cancel", "Cancelar", None, "Cancelar", "Cancel"),
    ("action_delete", "Eliminar", None, "Excluir", "Delete"),
    ("action_edit", "Editar", None, "Editar", "Edit"),
    ("action_add", "Agregar", None, "Adicionar", "Add"),
    ("action_share", "Compartir", None, "Compartilhar", "Share"),
    ("action_accept", "Aceptar", None, "Aceitar", "Accept"),
    ("action_close", "Cerrar", None, "Fechar", "Close"),
    ("action_next", "Siguiente", None, "Próximo", "Next"),
    ("action_start", "Iniciar", None, "Iniciar", "Start"),
    ("action_stop", "Detener", None, "Parar", "Stop"),
    ("action_export_pdf", "Exportar PDF", None, "Exportar PDF", "Export PDF"),
    ("action_export_csv", "Exportar CSV", None, "Exportar CSV", "Export CSV"),
    ("unit_liters", "L", None, "L", "L"),
    ("unit_ec", "mS/cm", None, "mS/cm", "mS/cm"),
    ("unit_celsius", "°C", None, "°C", "°C"),
    ("unit_percent", "%", None, "%", "%"),
    ("unit_ml", "mL", None, "mL", "mL"),
    ("unit_grams", "g", None, "g", "g"),
    ("unit_days", "días", None, "dias", "days"),
    ("unit_minutes", "min", None, "min", "min"),
    ("label_ph", "pH", None, "pH", "pH"),
    ("label_ec", "EC", None, "EC", "EC"),
    ("error_number", "Ingresa un número válido", None, "Digite um número válido", "Enter a valid number"),
    ("error_generic", "Algo salió mal: %1$s", None, "Algo deu errado: %1$s", "Something went wrong: %1$s"),
    ("saved_ok", "Guardado", None, "Salvo", "Saved"),
    # Navegación
    ("nav_systems", "Sistemas", None, "Sistemas", "Systems"),
    ("nav_formula", "Fórmula", None, "Fórmula", "Formula"),
    ("nav_log", "Bitácora", None, "Diário", "Log"),
    ("nav_diagnosis", "Diagnóstico", None, "Diagnóstico", "Diagnosis"),
    ("nav_more", "Más", None, "Mais", "More"),
    # Etapas y tipos de sistema
    ("stage_plantula", "Plántula", None, "Plântula", "Seedling"),
    ("stage_vegetativa", "Vegetativa", None, "Vegetativa", "Vegetative"),
    ("stage_floracion", "Floración", None, "Floração", "Flowering"),
    ("stage_fructificacion", "Fructificación", None, "Frutificação", "Fruiting"),
    ("systype_dwc", "DWC (raíz profunda)", None, "DWC (raiz profunda)", "DWC (deep water)"),
    ("systype_nft", "NFT", None, "NFT", "NFT"),
    ("systype_kratky", "Kratky", None, "Kratky", "Kratky"),
    ("systype_tower", "Torre vertical", None, "Torre vertical", "Vertical tower"),
    ("systype_drip", "Goteo", None, "Gotejamento", "Drip"),
    ("systype_ebb", "Flujo y reflujo", None, "Fluxo e refluxo", "Ebb and flow"),
    ("systype_raft", "Raíz flotante", None, "Raiz flutuante", "Floating raft"),
    # Sistemas
    ("systems_new", "Nuevo sistema", None, "Novo sistema", "New system"),
    ("systems_edit", "Editar sistema", None, "Editar sistema", "Edit system"),
    ("systems_empty", "Aún no tienes sistemas. Agrega tu primer DWC, NFT o Kratky.", None, "Você ainda não tem sistemas. Adicione seu primeiro DWC, NFT ou Kratky.", "No systems yet. Add your first DWC, NFT or Kratky."),
    ("systems_summary", "%1$s · %2$s L · %3$s", None, "%1$s · %2$s L · %3$s", "%1$s · %2$s L · %3$s"),
    ("systems_photo", "Foto del sistema", None, "Foto do sistema", "System photo"),
    ("systems_name", "Nombre", None, "Nome", "Name"),
    ("systems_type", "Tipo de sistema", None, "Tipo de sistema", "System type"),
    ("systems_volume", "Volumen del reservorio", None, "Volume do reservatório", "Reservoir volume"),
    ("systems_location", "Ubicación", None, "Localização", "Location"),
    ("systems_pick_photo", "Elegir foto", None, "Escolher foto", "Choose photo"),
    ("systems_add_crop", "Agregar cultivo", None, "Adicionar cultivo", "Add crop"),
    ("systems_compatible", "Cultivos compatibles. pH común: %1$s · EC común: %2$s", None, "Cultivos compatíveis. pH comum: %1$s · EC comum: %2$s", "Compatible crops. Shared pH: %1$s · shared EC: %2$s"),
    ("systems_crops", "Cultivos en este reservorio", None, "Cultivos neste reservatório", "Crops in this reservoir"),
    ("systems_no_crops", "Sin cultivos asignados.", None, "Sem cultivos atribuídos.", "No crops assigned."),
    ("systems_delete_title", "¿Eliminar sistema?", None, "Excluir sistema?", "Delete system?"),
    ("systems_delete_text", "Se borrarán también sus cultivos y lecturas.", None, "Seus cultivos e leituras também serão excluídos.", "Its crops and readings will also be deleted."),
    ("systems_sown", "Siembra: %1$s", None, "Plantio: %1$s", "Sown: %1$s"),
    ("systems_harvest", "Cosecha estimada: %1$s", None, "Colheita estimada: %1$s", "Estimated harvest: %1$s"),
    ("systems_harvest_pending", "Cosecha estimada: dato pendiente", None, "Colheita estimada: dado pendente", "Estimated harvest: data pending"),
    ("systems_set_harvest", "Fijar fecha de cosecha", None, "Definir data de colheita", "Set harvest date"),
    ("systems_harvest_hint", "Los días por etapa sin fuente quedan como dato pendiente; puedes fijar la cosecha a mano.", None, "Dias por etapa sem fonte ficam como dado pendente; você pode definir a colheita manualmente.", "Days per stage without a source stay pending; you can set the harvest manually."),
    ("systems_stage", "Etapa actual", None, "Etapa atual", "Current stage"),
    ("timer_title", "Temporizador de ciclo", None, "Temporizador de ciclo", "Cycle timer"),
    ("timer_on", "Encendido", None, "Ligado", "On"),
    ("timer_off", "Apagado", None, "Desligado", "Off"),
    ("timer_state_on", "Bomba encendida · %1$s", None, "Bomba ligada · %1$s", "Pump on · %1$s"),
    ("timer_state_off", "Bomba apagada · %1$s", None, "Bomba desligada · %1$s", "Pump off · %1$s"),
    # Fórmula
    ("formula_title_step1", "Pedir fórmula", None, "Pedir fórmula", "Request formula"),
    ("formula_title_step2", "Tu fórmula", None, "Sua fórmula", "Your formula"),
    ("formula_saved", "Fórmulas guardadas", None, "Fórmulas salvas", "Saved formulas"),
    ("formula_saved_empty", "Aún no guardaste fórmulas.", None, "Você ainda não salvou fórmulas.", "No saved formulas yet."),
    ("formula_water_pure", "Agua de ósmosis o lluvia (0)", None, "Água de osmose ou chuva (0)", "Reverse-osmosis or rain water (0)"),
    ("formula_nl_title", "Pídela con tus palabras (opcional)", None, "Peça com suas palavras (opcional)", "Ask in your own words (optional)"),
    ("formula_nl_hint", "Ej.: fórmula para fresa en fructificación, 200 L, agua de pozo", None, "Ex.: fórmula para morango em frutificação, 200 L, água de poço", "E.g.: formula for strawberry in fruiting, 200 L, well water"),
    ("formula_nl_button", "Interpretar", None, "Interpretar", "Interpret"),
    ("formula_section_crop", "Cultivo y etapa", None, "Cultivo e etapa", "Crop and stage"),
    ("formula_crop", "Cultivo", None, "Cultivo", "Crop"),
    ("formula_source", "Fuente: %1$s", None, "Fonte: %1$s", "Source: %1$s"),
    ("formula_target_pending", "La meta nutricional de este cultivo y etapa es un dato pendiente. Elige una receta de referencia.", None, "A meta nutricional deste cultivo e etapa é um dado pendente. Escolha uma receita de referência.", "The nutrient target for this crop and stage is pending. Choose a reference recipe."),
    ("formula_recipe", "Receta de referencia", None, "Receita de referência", "Reference recipe"),
    ("formula_recipe_none", "Usar la meta del cultivo", None, "Usar a meta do cultivo", "Use the crop target"),
    ("formula_section_system", "Sistema, volumen y agua", None, "Sistema, volume e água", "System, volume and water"),
    ("formula_water", "Análisis de agua", None, "Análise de água", "Water analysis"),
    ("formula_add_water", "Agregar análisis de agua", None, "Adicionar análise de água", "Add water analysis"),
    ("formula_section_inputs", "Insumos que tienes", None, "Insumos que você tem", "Inputs you have"),
    ("formula_inputs_hint", "Marca lo que tienes. Los precios se editan en Compras.", None, "Marque o que você tem. Os preços são editados em Compras.", "Tick what you have. Prices are edited in Shopping."),
    ("formula_suggestions", "Te faltan insumos para cubrir la meta:", None, "Faltam insumos para cobrir a meta:", "You are missing inputs to cover the target:"),
    ("formula_section_stock", "Soluciones madre", None, "Soluções-mãe", "Stock solutions"),
    ("formula_factor", "Factor de concentración", None, "Fator de concentração", "Concentration factor"),
    ("formula_tank_volume", "Volumen de cada tanque", None, "Volume de cada tanque", "Volume of each tank"),
    ("formula_calculate", "Calcular fórmula", None, "Calcular fórmula", "Calculate formula"),
    ("formula_ec_estimated", "EC estimada", None, "EC estimada", "Estimated EC"),
    ("formula_ec_range", "Rango de EC del cultivo", None, "Faixa de EC do cultivo", "Crop EC range"),
    ("formula_ph_target", "pH objetivo", None, "pH alvo", "Target pH"),
    ("formula_cost", "Costo por 1 000 L", None, "Custo por 1 000 L", "Cost per 1,000 L"),
    ("formula_cost_pending", "agrega precios en Compras", None, "adicione preços em Compras", "add prices in Shopping"),
    ("formula_tank_direct", "Directo al reservorio", None, "Direto no reservatório", "Directly into the reservoir"),
    ("formula_tank_a", "Tanque A (calcio y hierro)", None, "Tanque A (cálcio e ferro)", "Tank A (calcium and iron)"),
    ("formula_tank_b", "Tanque B (sulfatos y fosfatos)", None, "Tanque B (sulfatos e fosfatos)", "Tank B (sulfates and phosphates)"),
    ("formula_tank_acid", "Tanque ácido", None, "Tanque ácido", "Acid tank"),
    ("formula_tank_dose", "Disuelve en %1$s L (%2$dx). Usa %3$s mL por litro: %4$s mL para %5$s L.", None, "Dissolva em %1$s L (%2$dx). Use %3$s mL por litro: %4$s mL para %5$s L.", "Dissolve in %1$s L (%2$dx). Use %3$s mL per liter: %4$s mL for %5$s L."),
    ("formula_acid_ml", "≈ %1$s mL de producto para %2$s L", None, "≈ %1$s mL de produto para %2$s L", "≈ %1$s mL of product for %2$s L"),
    ("formula_solubility_exceeded", "Se excede la solubilidad en este tanque. Usa un factor menor.", None, "A solubilidade é excedida neste tanque. Use um fator menor.", "Solubility is exceeded in this tank. Use a lower factor."),
    ("formula_balance", "ppm entregados contra meta", None, "ppm entregues vs. meta", "Delivered ppm vs. target"),
    ("formula_col_element", "Elem.", None, "Elem.", "Elem."),
    ("formula_col_target", "Meta", None, "Meta", "Target"),
    ("formula_col_delivered", "Entregado", None, "Entregue", "Delivered"),
    ("formula_col_dev", "Desvío", None, "Desvio", "Deviation"),
    ("formula_mass_balance", "Balance de masa verificado: error %1$s %%", None, "Balanço de massa verificado: erro %1$s %%", "Mass balance checked: error %1$s %%"),
    ("formula_explain_title", "Explicación", None, "Explicação", "Explanation"),
    ("formula_explain", "Explicar en lenguaje simple", None, "Explicar em linguagem simples", "Explain in plain language"),
    ("formula_ai_never_grams", "Los gramos los calcula el motor determinista; la IA solo explica.", None, "Os gramas são calculados pelo motor determinístico; a IA só explica.", "Grams are computed by the deterministic engine; AI only explains."),
    ("formula_safety", "Usa guantes y lentes con ácidos. Agrega siempre el ácido al agua.", None, "Use luvas e óculos com ácidos. Sempre adicione o ácido à água.", "Wear gloves and goggles with acids. Always add acid to water."),
    ("water_title", "Análisis de agua", None, "Análise de água", "Water analysis"),
    ("water_new", "Nuevo análisis", None, "Nova análise", "New analysis"),
    ("water_hint", "Ingresa los mg/L de tu laboratorio. El motor descuenta lo que ya trae el agua.", None, "Digite os mg/L do seu laboratório. O motor desconta o que a água já traz.", "Enter mg/L from your lab report. The engine subtracts what the water already provides."),
    ("water_name", "Nombre (ej.: pozo de la chacra)", None, "Nome (ex.: poço do sítio)", "Name (e.g.: farm well)"),
    # Onboarding
    ("onb_step", "Paso %1$d de %2$d", None, "Passo %1$d de %2$d", "Step %1$d of %2$d"),
    ("onb1_title", "Fórmulas exactas, sin internet", None, "Fórmulas exatas, sem internet", "Exact formulas, offline"),
    ("onb1_text", "Pide una fórmula para tu cultivo, etapa y volumen. APhid calcula los gramos por solución madre en tu teléfono, incluso en modo avión.", None, "Peça uma fórmula para seu cultivo, etapa e volume. O APhid calcula os gramas por solução-mãe no seu telefone, até em modo avião.", "Request a formula for your crop, stage and volume. APhid computes grams per stock solution on your phone, even in airplane mode."),
    ("onb2_title", "Tus datos se quedan contigo", None, "Seus dados ficam com você", "Your data stays with you"),
    ("onb2_text", "No necesitas cuenta. Todo se guarda en este teléfono. Nada se envía a la nube sin tu permiso explícito (Ley 29733).", None, "Você não precisa de conta. Tudo fica salvo neste telefone. Nada é enviado à nuvem sem sua permissão explícita.", "No account needed. Everything is stored on this phone. Nothing is sent to the cloud without your explicit permission."),
    ("onb3_title", "Alertas que cuidan tus raíces", None, "Alertas que cuidam das suas raízes", "Alerts that protect your roots"),
    ("onb3_text", "Te avisaremos si la solución pasa de 22 °C (riesgo de pudrición de raíz), si el pH o la EC salen de rango y cuándo toca cambiar la solución. Para eso necesitamos permiso de notificaciones.", None, "Avisaremos se a solução passar de 22 °C (risco de podridão de raiz), se o pH ou a EC saírem da faixa e quando trocar a solução. Para isso precisamos de permissão de notificações.", "We will warn you if the solution goes above 22 °C (root rot risk), if pH or EC drift out of range, and when to change the solution. This needs notification permission."),
    ("onb_skip", "Omitir", None, "Pular", "Skip"),
    ("onb_later", "Ahora no", None, "Agora não", "Not now"),
    ("onb_allow", "Permitir notificaciones", None, "Permitir notificações", "Allow notifications"),
]
