# Tabla de cadenas: (clave, es-PE, es-419 (None = igual), pt-BR, en)
STRINGS = [
    # Comunes
    ("app_name", "APhid", None, "APhid", "APhid"),
    ("pending_data", "dato pendiente", None, "dado pendente", "data pending"),
    ("cd_info", "Información", None, "Informação", "Information"),
    ("cd_warning", "Advertencia", None, "Aviso", "Warning"),
    ("cd_back", "Volver", None, "Voltar", "Back"),
    ("action_save", "Guardar", None, "Salvar", "Save"),
    ("action_cancel", "Cancelar", None, "Cancelar", "Cancel"),
    ("action_delete", "Eliminar", None, "Excluir", "Delete"),
    ("action_edit", "Editar", None, "Editar", "Edit"),
    ("action_add", "Agregar", None, "Adicionar", "Add"),
    ("action_share", "Compartir", None, "Compartilhar", "Share"),
    ("action_accept", "Aceptar", None, "Aceitar", "Accept"),
    ("action_close", "Cerrar", None, "Fechar", "Close"),
    ("action_next", "Siguiente", None, "Próximo", "Next"),
    ("action_start", "Iniciar", None, "Iniciar", "Start"),
    ("action_stop", "Detener", None, "Parar", "Stop"),
    ("action_export_pdf", "Exportar PDF", None, "Exportar PDF", "Export PDF"),
    ("action_export_csv", "Exportar CSV", None, "Exportar CSV", "Export CSV"),
    ("unit_liters", "L", None, "L", "L"),
    ("unit_ec", "mS/cm", None, "mS/cm", "mS/cm"),
    ("unit_celsius", "°C", None, "°C", "°C"),
    ("unit_percent", "%", None, "%", "%"),
    ("unit_ml", "mL", None, "mL", "mL"),
    ("unit_grams", "g", None, "g", "g"),
    ("unit_days", "días", None, "dias", "days"),
    ("unit_minutes", "min", None, "min", "min"),
    ("label_ph", "pH", None, "pH", "pH"),
    ("label_ec", "EC", None, "EC", "EC"),
    ("error_number", "Ingresa un número válido", None, "Digite um número válido", "Enter a valid number"),
    ("error_generic", "Algo salió mal: %1$s", None, "Algo deu errado: %1$s", "Something went wrong: %1$s"),
    ("saved_ok", "Guardado", None, "Salvo", "Saved"),
    # Navegación
    ("nav_systems", "Sistemas", None, "Sistemas", "Systems"),
    ("nav_formula", "Fórmula", None, "Fórmula", "Formula"),
    ("nav_log", "Bitácora", None, "Diário", "Log"),
    ("nav_diagnosis", "Diagnóstico", None, "Diagnóstico", "Diagnosis"),
    ("nav_more", "Más", None, "Mais", "More"),
    # Etapas y tipos de sistema
    ("stage_plantula", "Plántula", None, "Plântula", "Seedling"),
    ("stage_vegetativa", "Vegetativa", None, "Vegetativa", "Vegetative"),
    ("stage_floracion", "Floración", None, "Floração", "Flowering"),
    ("stage_fructificacion", "Fructificación", None, "Frutificação", "Fruiting"),
    ("systype_dwc", "DWC (raíz profunda)", None, "DWC (raiz profunda)", "DWC (deep water)"),
    ("systype_nft", "NFT", None, "NFT", "NFT"),
    ("systype_kratky", "Kratky", None, "Kratky", "Kratky"),
    ("systype_tower", "Torre vertical", None, "Torre vertical", "Vertical tower"),
    ("systype_drip", "Goteo", None, "Gotejamento", "Drip"),
    ("systype_ebb", "Flujo y reflujo", None, "Fluxo e refluxo", "Ebb and flow"),
    ("systype_raft", "Raíz flotante", None, "Raiz flutuante", "Floating raft"),
    # Sistemas
    ("systems_new", "Nuevo sistema", None, "Novo sistema", "New system"),
    ("systems_edit", "Editar sistema", None, "Editar sistema", "Edit system"),
    ("systems_empty", "Aún no tienes sistemas. Agrega tu primer DWC, NFT o Kratky.", None, "Você ainda não tem sistemas. Adicione seu primeiro DWC, NFT ou Kratky.", "No systems yet. Add your first DWC, NFT or Kratky."),
    ("systems_summary", "%1$s · %2$s L · %3$s", None, "%1$s · %2$s L · %3$s", "%1$s · %2$s L · %3$s"),
    ("systems_photo", "Foto del sistema", None, "Foto do sistema", "System photo"),
    ("systems_name", "Nombre", None, "Nome", "Name"),
    ("systems_type", "Tipo de sistema", None, "Tipo de sistema", "System type"),
    ("systems_volume", "Volumen del reservorio", None, "Volume do reservatório", "Reservoir volume"),
    ("systems_location", "Ubicación", None, "Localização", "Location"),
    ("systems_pick_photo", "Elegir foto", None, "Escolher foto", "Choose photo"),
    ("systems_add_crop", "Agregar cultivo", None, "Adicionar cultivo", "Add crop"),
    ("systems_compatible", "Cultivos compatibles. pH común: %1$s · EC común: %2$s", None, "Cultivos compatíveis. pH comum: %1$s · EC comum: %2$s", "Compatible crops. Shared pH: %1$s · shared EC: %2$s"),
    ("systems_crops", "Cultivos en este reservorio", None, "Cultivos neste reservatório", "Crops in this reservoir"),
    ("systems_no_crops", "Sin cultivos asignados.", None, "Sem cultivos atribuídos.", "No crops assigned."),
    ("systems_delete_title", "¿Eliminar sistema?", None, "Excluir sistema?", "Delete system?"),
    ("systems_delete_text", "Se borrarán también sus cultivos y lecturas.", None, "Seus cultivos e leituras também serão excluídos.", "Its crops and readings will also be deleted."),
    ("systems_sown", "Siembra: %1$s", None, "Plantio: %1$s", "Sown: %1$s"),
    ("systems_harvest", "Cosecha estimada: %1$s", None, "Colheita estimada: %1$s", "Estimated harvest: %1$s"),
    ("systems_harvest_pending", "Cosecha estimada: dato pendiente", None, "Colheita estimada: dado pendente", "Estimated harvest: data pending"),
    ("systems_set_harvest", "Fijar fecha de cosecha", None, "Definir data de colheita", "Set harvest date"),
    ("systems_harvest_hint", "Los días por etapa sin fuente quedan como dato pendiente; puedes fijar la cosecha a mano.", None, "Dias por etapa sem fonte ficam como dado pendente; você pode definir a colheita manualmente.", "Days per stage without a source stay pending; you can set the harvest manually."),
    ("systems_stage", "Etapa actual", None, "Etapa atual", "Current stage"),
    ("timer_title", "Temporizador de ciclo", None, "Temporizador de ciclo", "Cycle timer"),
    ("timer_on", "Encendido", None, "Ligado", "On"),
    ("timer_off", "Apagado", None, "Desligado", "Off"),
    ("timer_state_on", "Bomba encendida · %1$s", None, "Bomba ligada · %1$s", "Pump on · %1$s"),
    ("timer_state_off", "Bomba apagada · %1$s", None, "Bomba desligada · %1$s", "Pump off · %1$s"),
    # Fórmula
    ("formula_title_step1", "Pedir fórmula", None, "Pedir fórmula", "Request formula"),
    ("formula_title_step2", "Tu fórmula", None, "Sua fórmula", "Your formula"),
    ("formula_saved", "Fórmulas guardadas", None, "Fórmulas salvas", "Saved formulas"),
    ("formula_saved_empty", "Aún no guardaste fórmulas.", None, "Você ainda não salvou fórmulas.", "No saved formulas yet."),
    ("formula_water_pure", "Agua de ósmosis o lluvia (0)", None, "Água de osmose ou chuva (0)", "Reverse-osmosis or rain water (0)"),
    ("formula_nl_title", "Pídela con tus palabras (opcional)", None, "Peça com suas palavras (opcional)", "Ask in your own words (optional)"),
    ("formula_nl_hint", "Ej.: fórmula para fresa en fructificación, 200 L, agua de pozo", None, "Ex.: fórmula para morango em frutificação, 200 L, água de poço", "E.g.: formula for strawberry in fruiting, 200 L, well water"),
    ("formula_nl_button", "Interpretar", None, "Interpretar", "Interpret"),
    ("formula_section_crop", "Cultivo y etapa", None, "Cultivo e etapa", "Crop and stage"),
    ("formula_crop", "Cultivo", None, "Cultivo", "Crop"),
    ("formula_source", "Fuente: %1$s", None, "Fonte: %1$s", "Source: %1$s"),
    ("formula_target_pending", "La meta nutricional de este cultivo y etapa es un dato pendiente. Elige una receta de referencia.", None, "A meta nutricional deste cultivo e etapa é um dado pendente. Escolha uma receita de referência.", "The nutrient target for this crop and stage is pending. Choose a reference recipe."),
    ("formula_recipe", "Receta de referencia", None, "Receita de referência", "Reference recipe"),
    ("formula_recipe_none", "Usar la meta del cultivo", None, "Usar a meta do cultivo", "Use the crop target"),
    ("formula_section_system", "Sistema, volumen y agua", None, "Sistema, volume e água", "System, volume and water"),
    ("formula_water", "Análisis de agua", None, "Análise de água", "Water analysis"),
    ("formula_add_water", "Agregar análisis de agua", None, "Adicionar análise de água", "Add water analysis"),
    ("formula_section_inputs", "Insumos que tienes", None, "Insumos que você tem", "Inputs you have"),
    ("formula_inputs_hint", "Marca lo que tienes. Los precios se editan en Compras.", None, "Marque o que você tem. Os preços são editados em Compras.", "Tick what you have. Prices are edited in Shopping."),
    ("formula_suggestions", "Te faltan insumos para cubrir la meta:", None, "Faltam insumos para cobrir a meta:", "You are missing inputs to cover the target:"),
    ("formula_section_stock", "Soluciones madre", None, "Soluções-mãe", "Stock solutions"),
    ("formula_factor", "Factor de concentración", None, "Fator de concentração", "Concentration factor"),
    ("formula_tank_volume", "Volumen de cada tanque", None, "Volume de cada tanque", "Volume of each tank"),
    ("formula_calculate", "Calcular fórmula", None, "Calcular fórmula", "Calculate formula"),
    ("formula_ec_estimated", "EC estimada", None, "EC estimada", "Estimated EC"),
    ("formula_ec_range", "Rango de EC del cultivo", None, "Faixa de EC do cultivo", "Crop EC range"),
    ("formula_ph_target", "pH objetivo", None, "pH alvo", "Target pH"),
    ("formula_cost", "Costo por 1 000 L", None, "Custo por 1 000 L", "Cost per 1,000 L"),
    ("formula_cost_pending", "agrega precios en Compras", None, "adicione preços em Compras", "add prices in Shopping"),
    ("formula_tank_direct", "Directo al reservorio", None, "Direto no reservatório", "Directly into the reservoir"),
    ("formula_tank_a", "Tanque A (calcio y hierro)", None, "Tanque A (cálcio e ferro)", "Tank A (calcium and iron)"),
    ("formula_tank_b", "Tanque B (sulfatos y fosfatos)", None, "Tanque B (sulfatos e fosfatos)", "Tank B (sulfates and phosphates)"),
    ("formula_tank_acid", "Tanque ácido", None, "Tanque ácido", "Acid tank"),
    ("formula_tank_dose", "Disuelve en %1$s L (%2$dx). Usa %3$s mL por litro: %4$s mL para %5$s L.", None, "Dissolva em %1$s L (%2$dx). Use %3$s mL por litro: %4$s mL para %5$s L.", "Dissolve in %1$s L (%2$dx). Use %3$s mL per liter: %4$s mL for %5$s L."),
    ("formula_acid_ml", "≈ %1$s mL de producto para %2$s L", None, "≈ %1$s mL de produto para %2$s L", "≈ %1$s mL of product for %2$s L"),
    ("formula_solubility_exceeded", "Se excede la solubilidad en este tanque. Usa un factor menor.", None, "A solubilidade é excedida neste tanque. Use um fator menor.", "Solubility is exceeded in this tank. Use a lower factor."),
    ("formula_balance", "ppm entregados contra meta", None, "ppm entregues vs. meta", "Delivered ppm vs. target"),
    ("formula_col_element", "Elem.", None, "Elem.", "Elem."),
    ("formula_col_target", "Meta", None, "Meta", "Target"),
    ("formula_col_delivered", "Entregado", None, "Entregue", "Delivered"),
    ("formula_col_dev", "Desvío", None, "Desvio", "Deviation"),
    ("formula_mass_balance", "Balance de masa verificado: error %1$s %%", None, "Balanço de massa verificado: erro %1$s %%", "Mass balance checked: error %1$s %%"),
    ("formula_explain_title", "Explicación", None, "Explicação", "Explanation"),
    ("formula_explain", "Explicar en lenguaje simple", None, "Explicar em linguagem simples", "Explain in plain language"),
    ("formula_ai_never_grams", "Los gramos los calcula el motor determinista; la IA solo explica.", None, "Os gramas são calculados pelo motor determinístico; a IA só explica.", "Grams are computed by the deterministic engine; AI only explains."),
    ("formula_safety", "Usa guantes y lentes con ácidos. Agrega siempre el ácido al agua.", None, "Use luvas e óculos com ácidos. Sempre adicione o ácido à água.", "Wear gloves and goggles with acids. Always add acid to water."),
    ("water_title", "Análisis de agua", None, "Análise de água", "Water analysis"),
    ("water_new", "Nuevo análisis", None, "Nova análise", "New analysis"),
    ("water_hint", "Ingresa los mg/L de tu laboratorio. El motor descuenta lo que ya trae el agua.", None, "Digite os mg/L do seu laboratório. O motor desconta o que a água já traz.", "Enter mg/L from your lab report. The engine subtracts what the water already provides."),
    ("water_name", "Nombre (ej.: pozo de la chacra)", None, "Nome (ex.: poço do sítio)", "Name (e.g.: farm well)"),
    # Onboarding
    ("onb_step", "Paso %1$d de %2$d", None, "Passo %1$d de %2$d", "Step %1$d of %2$d"),
    ("onb1_title", "Fórmulas exactas, sin internet", None, "Fórmulas exatas, sem internet", "Exact formulas, offline"),
    ("onb1_text", "Pide una fórmula para tu cultivo, etapa y volumen. APhid calcula los gramos por solución madre en tu teléfono, incluso en modo avión.", None, "Peça uma fórmula para seu cultivo, etapa e volume. O APhid calcula os gramas por solução-mãe no seu telefone, até em modo avião.", "Request a formula for your crop, stage and volume. APhid computes grams per stock solution on your phone, even in airplane mode."),
    ("onb2_title", "Tus datos se quedan contigo", None, "Seus dados ficam com você", "Your data stays with you"),
    ("onb2_text", "No necesitas cuenta. Todo se guarda en este teléfono. Nada se envía a la nube sin tu permiso explícito (Ley 29733).", None, "Você não precisa de conta. Tudo fica salvo neste telefone. Nada é enviado à nuvem sem sua permissão explícita.", "No account needed. Everything is stored on this phone. Nothing is sent to the cloud without your explicit permission."),
    ("onb3_title", "Alertas que cuidan tus raíces", None, "Alertas que cuidam das suas raízes", "Alerts that protect your roots"),
    ("onb3_text", "Te avisaremos si la solución pasa de 22 °C (riesgo de pudrición de raíz), si el pH o la EC salen de rango y cuándo toca cambiar la solución. Para eso necesitamos permiso de notificaciones.", None, "Avisaremos se a solução passar de 22 °C (risco de podridão de raiz), se o pH ou a EC saírem da faixa e quando trocar a solução. Para isso precisamos de permissão de notificações.", "We will warn you if the solution goes above 22 °C (root rot risk), if pH or EC drift out of range, and when to change the solution. This needs notification permission."),
    ("onb_skip", "Omitir", None, "Pular", "Skip"),
    ("onb_later", "Ahora no", None, "Agora não", "Not now"),
    ("onb_allow", "Permitir notificaciones", None, "Permitir notificações", "Allow notifications"),
    # Bitácora
    ("log_no_systems", "Crea un sistema en la pestaña Sistemas para registrar lecturas.", None, "Crie um sistema na aba Sistemas para registrar leituras.", "Create a system in the Systems tab to log readings."),
    ("log_quick_entry", "Registro rápido", None, "Registro rápido", "Quick entry"),
    ("log_temp_solution", "T. solución", None, "T. solução", "Solution temp."),
    ("log_temp_air", "T. aire", None, "T. ar", "Air temp."),
    ("log_humidity", "Humedad relativa", None, "Umidade relativa", "Relative humidity"),
    ("log_volume", "Volumen restante", None, "Volume restante", "Remaining volume"),
    ("log_drift_title", "¿Por qué cambió?", None, "Por que mudou?", "Why did it change?"),
    ("log_chart_title", "Tendencia y zona óptima", None, "Tendência e zona ótima", "Trend and optimal zone"),
    ("log_chart_empty", "Registra al menos 2 lecturas para ver el gráfico.", None, "Registre pelo menos 2 leituras para ver o gráfico.", "Log at least 2 readings to see the chart."),
    ("log_chart_cd", "Gráfico de lecturas con banda de zona óptima", None, "Gráfico de leituras com faixa de zona ótima", "Readings chart with optimal zone band"),
    ("log_chart_axis", "Eje horizontal: horas desde la primera lectura. Banda: zona óptima del cultivo.", None, "Eixo horizontal: horas desde a primeira leitura. Faixa: zona ótima do cultivo.", "Horizontal axis: hours since the first reading. Band: crop optimal zone."),
    ("log_band_pending", "Zona óptima: dato pendiente para los cultivos de este sistema.", None, "Zona ótima: dado pendente para os cultivos deste sistema.", "Optimal zone: data pending for this system's crops."),
    # Calculadoras
    ("calc_title", "Calculadoras", None, "Calculadoras", "Calculators"),
    ("calc_ecppm", "Conversión EC ↔ ppm", None, "Conversão EC ↔ ppm", "EC ↔ ppm conversion"),
    ("calc_scale", "Escala", None, "Escala", "Scale"),
    ("calc_ph", "Corrección de pH por volumen", None, "Correção de pH por volume", "pH correction by volume"),
    ("calc_ph_hint", "Haz una prueba: agrega un poco de corrector a un balde medido y anota cuánto cambió el pH. La app escala la dosis a tu reservorio.", None, "Faça um teste: adicione um pouco de corretor a um balde medido e anote quanto o pH mudou. O app escala a dose para seu reservatório.", "Run a test: add a little corrector to a measured bucket and note how much the pH changed. The app scales the dose to your reservoir."),
    ("calc_ph_delta", "Cambio de pH que necesitas", None, "Mudança de pH necessária", "pH change you need"),
    ("calc_test_ml", "Prueba: mL", None, "Teste: mL", "Test: mL"),
    ("calc_test_l", "en L", None, "em L", "in L"),
    ("calc_test_delta", "cambió pH", None, "mudou pH", "pH changed"),
    ("calc_total", "Dosis total estimada", None, "Dose total estimada", "Estimated total dose"),
    ("calc_first_step", "Primer paso (la mitad): agrega, espera 15 min y mide", None, "Primeiro passo (metade): adicione, espere 15 min e meça", "First step (half): add, wait 15 min and measure"),
    ("calc_acid", "Ácido según la alcalinidad del agua", None, "Ácido conforme a alcalinidade da água", "Acid from water alkalinity"),
    ("calc_acid_product", "Ácido", None, "Ácido", "Acid"),
    ("calc_replenish", "Reposición del reservorio", None, "Reposição do reservatório", "Reservoir top-up"),
    ("calc_full", "Volumen lleno", None, "Volume cheio", "Full volume"),
    ("calc_remaining", "Queda", None, "Resta", "Remaining"),
    ("calc_ec_now", "EC actual", None, "EC atual", "Current EC"),
    ("calc_ec_target", "EC meta", None, "EC meta", "Target EC"),
    # Diagnóstico
    ("diag_take_photo", "Tomar foto", None, "Tirar foto", "Take photo"),
    ("diag_disclaimer", "Diagnóstico orientativo. Confirme con un especialista.", None, "Diagnóstico orientativo. Confirme com um especialista.", "Guidance only. Confirm with a specialist."),
    ("diag_empty", "Aún no hay diagnósticos.", None, "Ainda não há diagnósticos.", "No diagnoses yet."),
    ("diag_camera_why", "Para fotografiar hojas y raíces, APhid necesita usar la cámara. Las fotos se quedan en tu teléfono.", None, "Para fotografar folhas e raízes, o APhid precisa usar a câmera. As fotos ficam no seu telefone.", "To photograph leaves and roots, APhid needs the camera. Photos stay on your phone."),
    ("diag_camera_allow", "Permitir cámara", None, "Permitir câmera", "Allow camera"),
    ("diag_shutter", "Capturar", None, "Capturar", "Capture"),
    ("diag_photo_cd", "Foto a diagnosticar", None, "Foto para diagnosticar", "Photo to diagnose"),
    ("diag_notes", "Síntomas que observas (opcional)", None, "Sintomas que você observa (opcional)", "Symptoms you see (optional)"),
    ("diag_analyze_local", "Analizar en el teléfono", None, "Analisar no telefone", "Analyze on phone"),
    ("diag_analyze_cloud", "Analizar en la nube", None, "Analisar na nuvem", "Analyze in the cloud"),
    ("diag_retake", "Otra foto", None, "Outra foto", "Retake"),
    ("diag_cloud_pro", "El análisis en la nube es parte de APhid Pro y siempre pide tu permiso por foto.", None, "A análise na nuvem faz parte do APhid Pro e sempre pede sua permissão por foto.", "Cloud analysis is part of APhid Pro and always asks your permission per photo."),
    ("diag_recheck", "Recordarme revisar en %1$d días", None, "Lembrar de revisar em %1$d dias", "Remind me to recheck in %1$d days"),
    ("diag_confidence", "Confianza: %1$s %% · Fuente: %2$s", None, "Confiança: %1$s %% · Fonte: %2$s", "Confidence: %1$s %% · Source: %2$s"),
    ("diag_urgency", "Urgencia: %1$s", None, "Urgência: %1$s", "Urgency: %1$s"),
    ("diag_evidence", "Evidencias", None, "Evidências", "Evidence"),
    ("diag_actions", "Acciones sugeridas", None, "Ações sugeridas", "Suggested actions"),
    # Consentimiento (Ley 29733)
    ("consent_title", "¿Enviar esta foto a la nube?", None, "Enviar esta foto para a nuvem?", "Send this photo to the cloud?"),
    ("consent_photo_text", "La foto y tus notas se enviarán a nuestro servidor y a Anthropic (Claude) solo para este diagnóstico. No se usan para publicidad y puedes revocar este permiso en Ajustes. Base legal: tu consentimiento expreso (Ley 29733, Perú).", None, "A foto e suas notas serão enviadas ao nosso servidor e à Anthropic (Claude) apenas para este diagnóstico. Não são usadas para publicidade e você pode revogar esta permissão em Ajustes.", "The photo and your notes will be sent to our server and to Anthropic (Claude) only for this diagnosis. They are not used for advertising and you can revoke this permission in Settings."),
    ("consent_accept", "Sí, enviar esta foto", None, "Sim, enviar esta foto", "Yes, send this photo"),
    ("consent_reject", "No enviar", None, "Não enviar", "Don't send"),
    # Alertas y tareas
    ("alerts_title", "Alertas y recordatorios", None, "Alertas e lembretes", "Alerts and reminders"),
    ("alerts_permission_why", "Activa las notificaciones para enterarte a tiempo si la solución se calienta (riesgo de pudrición de raíz), si el pH o la EC se desvían o si falla la bomba.", None, "Ative as notificações para saber a tempo se a solução esquentar, se o pH ou a EC desviarem ou se a bomba falhar.", "Turn on notifications to know in time if the solution gets warm, if pH or EC drift, or if the pump fails."),
    ("alerts_check_now", "Revisar ahora", None, "Verificar agora", "Check now"),
    ("alerts_clear", "Borrar alertas", None, "Limpar alertas", "Clear alerts"),
    ("alerts_section", "Alertas", None, "Alertas", "Alerts"),
    ("alerts_none", "Sin alertas. La bitácora se revisa cada 6 horas, también sin internet.", None, "Sem alertas. O diário é verificado a cada 6 horas, também sem internet.", "No alerts. The log is checked every 6 hours, even offline."),
    ("tasks_section", "Recordatorios", None, "Lembretes", "Reminders"),
    ("tasks_add", "Nuevo recordatorio", None, "Novo lembrete", "New reminder"),
    ("tasks_every", "cada %1$d días", None, "a cada %1$d dias", "every %1$d days"),
    ("tasks_kind", "Tipo", None, "Tipo", "Type"),
    ("tasks_title", "Descripción", None, "Descrição", "Description"),
    ("tasks_in_days", "Dentro de", None, "Daqui a", "In"),
    ("tasks_repeat", "Repetir cada (opcional)", None, "Repetir a cada (opcional)", "Repeat every (optional)"),
    ("task_change_solution", "Cambio de solución", None, "Troca de solução", "Solution change"),
    ("task_cleaning", "Limpieza del sistema", None, "Limpeza do sistema", "System cleaning"),
    ("task_calibration", "Calibración de medidores", None, "Calibração de medidores", "Meter calibration"),
    ("task_roots", "Inspección de raíces", None, "Inspeção de raízes", "Root inspection"),
    ("task_pests", "Revisión de plagas", None, "Revisão de pragas", "Pest check"),
    ("task_other", "Otra", None, "Outra", "Other"),
    # Cultivos
    ("crops_title", "Cultivos", None, "Cultivos", "Crops"),
    ("crops_compat", "Compatibilidad de cultivos", None, "Compatibilidade de cultivos", "Crop compatibility"),
    ("crops_compat_hint", "Agrega los cultivos que compartirán un mismo reservorio para comparar sus rangos de pH y EC.", None, "Adicione os cultivos que compartilharão o mesmo reservatório para comparar suas faixas de pH e EC.", "Add the crops that will share a reservoir to compare their pH and EC ranges."),
    ("crops_check", "Verificar", None, "Verificar", "Check"),
    ("crops_no_invent", "APhid no inventa valores agronómicos: lo que no tiene fuente aparece como dato pendiente.", None, "O APhid não inventa valores agronômicos: o que não tem fonte aparece como dado pendente.", "APhid does not invent agronomic values: anything without a source shows as pending."),
    ("crops_days", "Días de la etapa", None, "Dias da etapa", "Days in stage"),
    ("crops_ppm", "Metas en ppm", None, "Metas em ppm", "ppm targets"),
    ("crops_by_recipe", "según receta: %1$s", None, "conforme receita: %1$s", "from recipe: %1$s"),
    # Plagas
    ("pests_title", "Plagas (MIP)", None, "Pragas (MIP)", "Pests (IPM)"),
    ("pests_intro", "Manejo integrado: identifica, monitorea y prefiere el control físico y biológico.", None, "Manejo integrado: identifique, monitore e prefira o controle físico e biológico.", "Integrated management: identify, monitor and prefer physical and biological control."),
    ("pests_identification", "Identificación", None, "Identificação", "Identification"),
    ("pests_threshold", "Umbral de acción", None, "Limiar de ação", "Action threshold"),
    ("pests_physical", "Control físico", None, "Controle físico", "Physical control"),
    ("pests_biological", "Control biológico", None, "Controle biológico", "Biological control"),
    ("pests_record", "Registrar observación", None, "Registrar observação", "Record observation"),
    ("pests_count", "Individuos por hoja (opcional)", None, "Indivíduos por folha (opcional)", "Individuals per leaf (optional)"),
    ("pests_save_and_remind", "Guardar y recordar en %1$d días", None, "Salvar e lembrar em %1$d dias", "Save and remind in %1$d days"),
    ("pests_history", "Historial", None, "Histórico", "History"),
    # Compras
    ("shop_title", "Compras y costos", None, "Compras e custos", "Shopping and costs"),
    ("shop_catalog", "Catálogo de insumos", None, "Catálogo de insumos", "Input catalog"),
    ("shop_no_formula", "Guarda una fórmula para generar su lista de compras.", None, "Salve uma fórmula para gerar a lista de compras.", "Save a formula to generate its shopping list."),
    ("shop_batches", "Número de preparaciones de tanques", None, "Número de preparos de tanques", "Number of tank batches"),
    ("shop_list", "Lista de compras", None, "Lista de compras", "Shopping list"),
    ("shop_total", "Total", None, "Total", "Total"),
    ("shop_missing_price", "Algunos insumos no tienen precio: agrégalo en el catálogo.", None, "Alguns insumos não têm preço: adicione no catálogo.", "Some inputs have no price: add it in the catalog."),
    ("shop_costs", "Costos", None, "Custos", "Costs"),
    ("shop_cost_liter", "Costo por litro de solución", None, "Custo por litro de solução", "Cost per liter of solution"),
    ("shop_liters_harvest", "Litros usados por cosecha", None, "Litros usados por colheita", "Liters used per harvest"),
    ("shop_cost_harvest", "Costo por cosecha", None, "Custo por colheita", "Cost per harvest"),
    ("shop_new_input", "Nuevo insumo", None, "Novo insumo", "New input"),
    ("shop_no_price", "sin precio", None, "sem preço", "no price"),
    ("shop_verify_label", "verifica la etiqueta", None, "verifique o rótulo", "check the label"),
    ("shop_formula", "Fórmula química", None, "Fórmula química", "Chemical formula"),
    ("shop_price", "Precio", None, "Preço", "Price"),
    ("shop_purity", "Pureza", None, "Pureza", "Purity"),
    ("shop_supplier", "Proveedor local", None, "Fornecedor local", "Local supplier"),
    ("shop_solubility", "Solubilidad a 20 °C", None, "Solubilidade a 20 °C", "Solubility at 20 °C"),
    ("shop_tank", "Tanque preferido", None, "Tanque preferido", "Preferred tank"),
    ("shop_composition", "Composición (% p/p del elemento)", None, "Composição (% p/p do elemento)", "Composition (% w/w of element)"),
    # Ajustes
    ("settings_title", "Ajustes", None, "Ajustes", "Settings"),
    ("settings_alerts", "Alertas", None, "Alertas", "Alerts"),
    ("settings_alerts_enabled", "Alertas predictivas", None, "Alertas preditivos", "Predictive alerts"),
    ("settings_temp_max", "Temperatura máxima de la solución", None, "Temperatura máxima da solução", "Maximum solution temperature"),
    ("settings_sensors", "Tengo sensores (vigilar latido cada 15 min)", None, "Tenho sensores (vigiar sinal a cada 15 min)", "I have sensors (watch heartbeat every 15 min)"),
    ("settings_units", "Unidades y agua", None, "Unidades e água", "Units and water"),
    ("settings_hco3_limit", "Límite de bicarbonato para usar ácido", None, "Limite de bicarbonato para usar ácido", "Bicarbonate limit to use acid"),
    ("settings_hco3_residual", "Bicarbonato residual (reserva tampón)", None, "Bicarbonato residual (reserva tampão)", "Residual bicarbonate (buffer)"),
    ("settings_privacy", "Privacidad", None, "Privacidade", "Privacy"),
    ("settings_cloud_consent", "Permitir IA en la nube para texto", None, "Permitir IA na nuvem para texto", "Allow cloud AI for text"),
    ("settings_cloud_consent_hint", "Desactivado por defecto. Las fotos siempre piden permiso una por una.", None, "Desativado por padrão. As fotos sempre pedem permissão uma a uma.", "Off by default. Photos always ask permission one by one."),
    ("settings_telemetry", "Telemetría anónima", None, "Telemetria anônima", "Anonymous telemetry"),
    ("settings_telemetry_hint", "Desactivada por defecto. APhid no envía datos de uso mientras esté apagada.", None, "Desativada por padrão. O APhid não envia dados de uso enquanto estiver desligada.", "Off by default. APhid sends no usage data while it is off."),
    ("settings_sync", "Sincronización en la nube (Pro)", None, "Sincronização na nuvem (Pro)", "Cloud sync (Pro)"),
    ("settings_sync_hint", "Opcional y desactivada por defecto. Tus datos viven en el teléfono.", None, "Opcional e desativada por padrão. Seus dados ficam no telefone.", "Optional and off by default. Your data lives on the phone."),
    ("settings_backup", "Respaldo manual", None, "Backup manual", "Manual backup"),
    ("settings_backup_hint", "Exporta o importa toda tu información como archivo JSON. Guárdalo donde tú elijas.", None, "Exporte ou importe todas as suas informações como arquivo JSON.", "Export or import all your data as a JSON file."),
    ("settings_export", "Exportar JSON", None, "Exportar JSON", "Export JSON"),
    ("settings_import", "Importar JSON", None, "Importar JSON", "Import JSON"),
    ("settings_delete_all", "Borrar todos mis datos", None, "Apagar todos os meus dados", "Delete all my data"),
    ("settings_delete_text", "Se borrarán sistemas, lecturas, fórmulas, fotos, alertas y ajustes de este teléfono. No se puede deshacer.", None, "Sistemas, leituras, fórmulas, fotos, alertas e ajustes deste telefone serão apagados. Não pode ser desfeito.", "Systems, readings, formulas, photos, alerts and settings on this phone will be deleted. This cannot be undone."),
    # Privacidad
    ("privacy_title", "Política de privacidad", None, "Política de privacidade", "Privacy policy"),
    ("privacy_p1", "Responsable: el equipo de APhid. Cumplimos la Ley N.° 29733 de Protección de Datos Personales del Perú y su reglamento (D. S. 016-2024-JUS).", None, "Responsável: a equipe do APhid. Cumprimos a Lei peruana 29733 de Proteção de Dados Pessoais e seu regulamento.", "Controller: the APhid team. We comply with Peru's Personal Data Protection Law 29733 and its regulation (S.D. 016-2024-JUS)."),
    ("privacy_p2", "Datos locales por defecto: tus sistemas, lecturas, fórmulas y fotos se guardan solo en este teléfono. No pedimos cuenta ni nombre.", None, "Dados locais por padrão: sistemas, leituras, fórmulas e fotos ficam só neste telefone. Não pedimos conta nem nome.", "Local data by default: your systems, readings, formulas and photos are stored only on this phone. No account or name required."),
    ("privacy_p3", "Nube solo con tu consentimiento expreso: si eliges analizar una foto en la nube, esa foto y tus notas se envían a nuestro servidor y a Anthropic (Claude) únicamente para ese diagnóstico.", None, "Nuvem só com seu consentimento expresso: ao analisar uma foto na nuvem, ela e suas notas são enviadas ao nosso servidor e à Anthropic apenas para esse diagnóstico.", "Cloud only with your express consent: if you analyze a photo in the cloud, that photo and your notes go to our server and to Anthropic (Claude) only for that diagnosis."),
    ("privacy_p4", "No usamos tus datos para publicidad. La telemetría está desactivada por defecto. El respaldo automático en la nube de Android está desactivado.", None, "Não usamos seus dados para publicidade. A telemetria está desativada por padrão.", "We do not use your data for advertising. Telemetry is off by default. Android cloud auto-backup is disabled."),
    ("privacy_p5", "Tus derechos (ARCO): acceder, rectificar, cancelar y oponerte. Puedes exportar todo en JSON o usar \"Borrar todos mis datos\" en Ajustes en cualquier momento.", None, "Seus direitos: acessar, retificar, cancelar e se opor. Exporte tudo em JSON ou use \"Apagar todos os meus dados\" em Ajustes.", "Your rights: access, rectify, cancel and object. Export everything as JSON or use \"Delete all my data\" in Settings at any time."),
    ("privacy_p6", "Contacto: privacidad@aphid.pe. Puedes presentar un reclamo ante la Autoridad Nacional de Protección de Datos Personales (MINJUSDH).", None, "Contato: privacidad@aphid.pe.", "Contact: privacidad@aphid.pe. You may file a complaint with Peru's National Data Protection Authority."),
    # Pro
    ("pro_title", "APhid Pro", None, "APhid Pro", "APhid Pro"),
    ("pro_summary", "Opcional: diagnóstico en la nube y sincronización.", None, "Opcional: diagnóstico na nuvem e sincronização.", "Optional: cloud diagnosis and sync."),
    ("pro_active", "APhid Pro activo. ¡Gracias!", None, "APhid Pro ativo. Obrigado!", "APhid Pro active. Thank you!"),
    ("pro_more", "Ver APhid Pro", None, "Ver APhid Pro", "See APhid Pro"),
    ("pro_free_core", "Fórmulas, bitácora, alertas, calculadoras y exportación son y seguirán siendo gratis.", None, "Fórmulas, diário, alertas, calculadoras e exportação são e continuarão gratuitos.", "Formulas, log, alerts, calculators and export are and will stay free."),
    ("pro_includes", "Pro incluye: diagnóstico por foto en la nube (con permiso por foto) y sincronización opcional entre dispositivos.", None, "Pro inclui: diagnóstico por foto na nuvem e sincronização opcional.", "Pro includes: cloud photo diagnosis (with per-photo permission) and optional sync across devices."),
    ("pro_buy", "Suscribirme", None, "Assinar", "Subscribe"),
    ("pro_buy_price", "Suscribirme por %1$s", None, "Assinar por %1$s", "Subscribe for %1$s"),
    # Sensores
    ("sensors_title", "Sensores", None, "Sensores", "Sensors"),
    ("sensors_intro", "Conecta un nodo ESP32 con pH, EC, temperatura y nivel por Bluetooth (BLE) o por Wi-Fi (MQTT). Las lecturas se guardan solas en la bitácora.", None, "Conecte um nó ESP32 com pH, EC, temperatura e nível por Bluetooth (BLE) ou Wi-Fi (MQTT). As leituras são salvas sozinhas no diário.", "Connect an ESP32 node with pH, EC, temperature and level over Bluetooth (BLE) or Wi-Fi (MQTT). Readings are saved to the log automatically."),
    ("sensors_target", "Guardar lecturas en el sistema", None, "Salvar leituras no sistema", "Save readings to system"),
    ("sensors_ble", "Bluetooth (BLE GATT)", None, "Bluetooth (BLE GATT)", "Bluetooth (BLE GATT)"),
    ("sensors_scan", "Buscar nodos", None, "Buscar nós", "Scan for nodes"),
    ("sensors_disconnect", "Desconectar", None, "Desconectar", "Disconnect"),
    ("sensors_connected", "Conectado a %1$s", None, "Conectado a %1$s", "Connected to %1$s"),
    ("sensors_mqtt", "Wi-Fi (MQTT, opcional)", None, "Wi-Fi (MQTT, opcional)", "Wi-Fi (MQTT, optional)"),
    ("sensors_host", "Broker (IP local)", None, "Broker (IP local)", "Broker (local IP)"),
    ("sensors_port", "Puerto", None, "Porta", "Port"),
    ("sensors_node", "Nodo", None, "Nó", "Node"),
    ("sensors_connect", "Conectar", None, "Conectar", "Connect"),
    ("sensors_mqtt_hint", "Temas: aphid/<nodo>/lectura (JSON) y aphid/<nodo>/latido. Solo red local sin TLS.", None, "Tópicos: aphid/<nó>/lectura (JSON) e aphid/<nó>/latido. Somente rede local sem TLS.", "Topics: aphid/<node>/lectura (JSON) and aphid/<node>/latido. Local network only, no TLS."),
    ("sensors_last", "Última medición", None, "Última medição", "Last measurement"),
    ("sensors_level", "Nivel", None, "Nível", "Level"),
    ("sensors_profile", "Perfil BLE GATT", None, "Perfil BLE GATT", "BLE GATT profile"),
    ("sensors_heartbeat_hint", "El nodo envía un latido cada 5 min. Si falta 15 min, recibirás la alerta \"posible corte de energía o bomba\".", None, "O nó envia um sinal a cada 5 min. Se faltar 15 min, você receberá o alerta \"possível corte de energia ou bomba\".", "The node sends a heartbeat every 5 min. If missing for 15 min, you get a \"possible power or pump failure\" alert."),
    # Más
    ("more_crops", "Cultivos y compatibilidad", None, "Cultivos e compatibilidade", "Crops and compatibility"),
    ("more_pests", "Plagas (MIP)", None, "Pragas (MIP)", "Pests (IPM)"),
    ("more_shopping", "Compras y costos", None, "Compras e custos", "Shopping and costs"),
    ("more_sensors", "Sensores", None, "Sensores", "Sensors"),
    ("more_alerts", "Alertas y recordatorios", None, "Alertas e lembretes", "Alerts and reminders"),
    ("more_calculators", "Calculadoras", None, "Calculadoras", "Calculators"),
    ("more_settings", "Ajustes y privacidad", None, "Ajustes e privacidade", "Settings and privacy"),
]
